name: Arkson Official
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/be441b19-2854-4165-b16f-7ab9cc22fb0b.png
color:
  saturation: 0.4462366
  brandStrength: 0.4623656
  lightness: 0.4155447
  brandColors:
    - '#AFB8BF'
    - '#1A1E21'
    - '#D7DEE4'
    - '#545861'
    - '#777E86'
  rhythmicContrast: 0.6070293
typography_spectrum: 0.2867384
navigation:
  - name: Bio
    id: 26689a15-35de-4266-8d12-c0ed7e9e2394
    type: content
  - name: Listen
    id: 1ea53373-78e9-46a0-bedc-0755bdd5b30e
    type: content
layout_spectrum: 0.5035842
content_rating:
  adult: false
